### ISSUE TITLE
newcomer: info and FAQ on the project

### ISSUE THREAD

**Issue by andreabenini** [openmessaging/specification#1]
Hi,
I have just [read information](https://www.linuxfoundation.org/blog/building-open-standard-distributed-messaging-introducing-openmessaging/) about this project from main Linux Foundation website and after that I have navigated the github repo as well as pages from [this site](http://openmessaging.cloud). Website, information and the entire initiative is totally new and I'm aware of it, I'm not arguing against a possible lack of code or data because it's normal but I'm still trying to figure out what kind of road plan you have decided to follow and what are main goals for the Project.
I have few basic questions because I'd like to evaluate if I can help or contribute in some way:

- Instant Messaging is an abused concept nowadays so I'd like to understand if this "messaging" is related to specific services (web portals, social networks, ..), devices (pc, mobile, IoT), protocols (IRC, SIMPLE, XMPP, ...), queue brokers (ie: rabbit) or whatever
- interaction/gateways with other (existing) services (IRC,XMPP) or proprietary vendor solutions (MS,Google,Vidyo,...)
- overall system architecture: cloud/host based, peer to peer, server based, ...
- I have seen various repos but I didn't get a clear idea if you're focusing on the client side only or if you're interested on the server side or both
- `the nice thing about standards is that you have so many to choose from` is a well known citation and I'm trying to understand differences between you and other proposed 'standards' (example: xmpp foundation)
- Possible interaction between you and other: instant messaging services, message brokers, broadcast services
- opening an issue for these basic questions is rather stupid but I'd like to understand favorite channels you have planned to use to interact with the community (ML,slack,github,...)

Few|many questions here are probably out of your scope but I still like to ask because even if you're in your early days I'm considering it because seems to be an useful initiative

Best Wishes
Regards
Ben

**Comment by vongosling** [comment]
I am so sorry to respond your question until now :-) Did you read our domain arch. and use case for openmessaging spec.? If you have any question, dont' hesitate to ping me at [slack channel](https://openmessaging.slack.com/messages/C6XMXNZN2/details/)

**Comment by andreabenini** [comment]
Thanks for your reply,
From what you published right now in the architecture section I have now understood what this projects wants to achieve. 
Thanks for your comment.
