### ISSUE TITLE
Some issues about the use case.

### ISSUE THREAD

**Issue by Jason918** [openmessaging/specification#10]
1. Common UseCases 4. Highway/assets/images/use_cases
In the following explanation in the document, it only describes the Highway. Nothing is mentioned about "assets/images/use_cases".

2. What's SequenceProducer and StreamingConsumer? 
Why is SequenceProducer and StreamingConsumer just pop up in the use case section？ Maybe we should add some definition first ?

**Comment by duhengforever** [comment]
This issue has been resolved, thanks for your review.
