### ISSUE TITLE
It should support low-end microcontrollers from start

### ISSUE THREAD

**Issue by acassis** [openmessaging/specification#2]
Dear Linux Foundation guys, please think out of the box and add support for cloud message communication that will work for low-end microcontrollers as well. Maybe it could have levels/types/profiles of supported messages.

Note that AliOS will use STM32F2 microcontrollers for their cloud systems, then it important to support microcontrollers with low memory (KBs instead of MBs) :
http://www.nasdaq.com/press-release/stmicroelectronics-combines-unique-development-ecosystem-with-alibaba-alios-for-first-chinese-20171013-00109

**Comment by vongosling** [comment]
well, microcontrollers seem to an implementation, openmessaging is consider to be a cloud messaging standard like SQL in Db industry :-)

**Comment by zhouxinyu** [comment]
Thanks, @acassis, any further question/advice is welcome, we will close the issue now.
